version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'direct'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      jest:
        patterns:
          - 'jest'
          - '@jest/*'
          - 'jest-environment-*'
      size-limit:
        patterns:
          - 'size-limit'
          - '@size-limit/*'
    reviewers:
      - 'VKCOM/vk-sec'

  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'VKCOM/vk-sec'
