name: 'Reusable workflow / Unit tests'

on:
  workflow_call:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        default: ${{ github.ref }}
        required: false
        type: string

jobs:
  test:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --ignore-scripts

      - name: Run tests
        run: yarn run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
