name: 'Reusable workflow / Unit tests'

on:
  workflow_call:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        default: ${{ github.ref }}
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --ignore-scripts

      - name: Run lints
        run: yarn run lint

      - name: Run tests
        run: yarn run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
